### ISSUE TITLE
Using Opera for scenario generation

### ISSUE THREAD

**Issue by elalaouifaris** [Dralliag/opera#7]
Dear Opera team,

I would like to thank you for sharing this package with the R community.

This issue is for asking a question regarding the potential use of opera as a predictor aggregator for simulation purposes instead of prediction.

The idea is that in some contexts we need to generate scenarios of a number of time series. Depending on the application these time series have different behaviors (some have periodicities, others are better modeled as noise and all the gradations between these 2 extremes). 

The workflow that I have in mind is the following:
+ Define families of models that are relevant for the application.
+ Calibrate the models based on a portion of the historical data eventually selecting the best model in sub-families of models. The predictors can include external time series (for which we can have simulations for the future mainly like market data, weather, ... etc)
+ Use opera to calculate aggregation weights of the above predictors on a the remaining portion of the historical data. This gives a matrix of aggregation weights.
+ Use the generated weights matrix with additional features from calendar (days, months ... etc) and the external time series to build a training base. Apply a learning algorithm to predict the aggregation weights based on the relevant features. (Potential issue with the possible fast changes in the predicted weights: to be managed be including previous time step as a feature?)
+ Based on the above model use the external time series to predict the aggregation weights for the predictors and build a predicted trajectory for each scenario realisation of the input external time series.

Questions:
Do you have experience using opera in a system like this? The main objective is to generate scenarios that capture the key features of each signal without calibrating a model for each signal (in the case where we have too many signals to manage)

If we were to test this workflow, what parts could be included in the opera package itself, and which would be in an independent package? (a "simopera" as a name?)

Thank you very much!

Best ragards,
Faris

**Comment by ghost** [comment]
Hello Faris
We have not forgotten you ! We will come back to you as soon as possible.
Best
Raphaël

**Comment by Dralliag** [comment]
Ahh oui dsl Raphaël, en fait j'avais zappé… Je suis en conf pour deux semaines mais je vais essayer d'y répondre dès que possible (cette semaine) !
À bientôt,

Pierre

**Comment by elalaouifaris** [comment]
Hello,

Any feedback or new development on this topic?
Thank you!

**Comment by ghost** [comment]
Hello Faris, I will get back to you asap by private email.
